# Generated by Django 6.0.6 on 2026-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
